name: Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    name: 'Build'
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build
        shell: bash
        run: ./build.docker.sh

      - name: print logfiles and other info in case of failure
        if: ${{ failure() }}
        run: |
          echo ==== CMakeOutput.log ====
          cat build/CMakeFiles/CMakeOutput.log
          echo
          echo ==== CMakeError.log ====
          cat build/CMakeFiles/CMakeError.log
          echo ==== CMakeCache.txt ====
          cat build/CMakeCache.txt
      
      - name: Upload qtbase wasi install directory
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: qtbase-wasm32-wasi-install
          include-hidden-files: true
          path: ./wasm32-wasi-install/qtbase/**
      
      - name: Upload qtsvg wasi install directory
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: qtsvg-wasm32-wasi-install
          include-hidden-files: true
          path: ./wasm32-wasi-install/qtsvg/**
