name: Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    uses: ./.github/workflows/build-reusable.yml
    with:
      qtbase_branch: '6.10.3#wasi'
      qtsvg_branch: '6.10.3'
      create_release: false
